name: Test

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Test
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
          name: Check out repository
        - uses: actions/setup-node@v1
          name: Set up Node.js
          with:
            node-version: 12
        - run:  |
                npm ci
                npm run test